# Generated by Django 3.1.1 on 2020-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesionApp', '0002_auto_20200909_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='group_age',
            field=models.CharField(max_length=6),
        ),
    ]
