# Generated by Django 3.1.1 on 2020-09-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LesionApp', '0006_images_graphs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='graphs',
            new_name='pred_list',
        ),
    ]
