# Generated by Django 3.1.1 on 2020-09-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesionApp', '0008_auto_20200911_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
