# Generated by Django 3.1.1 on 2020-09-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LesionApp', '0009_images_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_type',
        ),
    ]
