# Generated by Django 3.1.1 on 2020-09-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LesionApp', '0011_auto_20200917_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
